/**
 * ROUND 25 — Kenney Food Kit (Selin'in kendi sağladığı, CC0 lisanslı gerçek
 * asset paketi; bkz. public/assets/packs/food-kit/ATTRIBUTION.md). Kaynak:
 * Kenney (kenney.nl), CC0.
 *
 * 3D model paketi (bkz. car-kit.js'teki aynı not) — kullanılan kaynak
 * `Previews/` render'ları. Ham pakette ~200 preview var (onlarca yiyecek +
 * varyant/kesilmiş/pişmiş hali). 17 asset seçildi: 8 çiğ malzeme
 * (collectible), 2 hedef obje (tabak/kesme tahtası — fruit-puzzle'ın
 * basket_red/basket_green ile AYNI "game-object + target" deseni), 3
 * mutfak aleti (gameObject), 4 hazır yemek (decoration — sahne zenginliği,
 * mock tarafından tüketilmiyor).
 *
 * Bu pack "cooking" adlı YENİ bir kitin (bkz. assetKits.js) tek asset
 * kaynağı — mevcut hiçbir kite eklenmedi (görsel/tema olarak diğer
 * kitlerden bağımsız).
 */
var FOOD_KIT_ASSETS = [
  // ---------------- collectible (8 çiğ malzeme) ----------------
  {
    id: "foodkit_apple",
    path: "/assets/packs/food-kit/objects/apple.png",
    category: "collectible",
    name: "Apple",
    tags: ["apple", "fruit", "ingredient", "collectible", "food", "kenney"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_banana",
    path: "/assets/packs/food-kit/objects/banana.png",
    category: "collectible",
    name: "Banana",
    tags: ["banana", "fruit", "ingredient", "collectible", "food", "kenney"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_tomato",
    path: "/assets/packs/food-kit/objects/tomato.png",
    category: "collectible",
    name: "Tomato",
    tags: ["tomato", "vegetable", "ingredient", "collectible", "food", "kenney"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_carrot",
    path: "/assets/packs/food-kit/objects/carrot.png",
    category: "collectible",
    name: "Carrot",
    tags: ["carrot", "vegetable", "ingredient", "collectible", "food", "kenney"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_egg",
    path: "/assets/packs/food-kit/objects/egg.png",
    category: "collectible",
    name: "Egg",
    tags: ["egg", "ingredient", "collectible", "food", "kenney"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_cheese",
    path: "/assets/packs/food-kit/objects/cheese.png",
    category: "collectible",
    name: "Cheese",
    tags: ["cheese", "ingredient", "collectible", "food", "kenney"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_bread",
    path: "/assets/packs/food-kit/objects/bread.png",
    category: "collectible",
    name: "Bread",
    tags: ["bread", "ingredient", "collectible", "food", "kenney"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_fish",
    path: "/assets/packs/food-kit/objects/fish.png",
    category: "collectible",
    name: "Fish",
    tags: ["fish", "ingredient", "collectible", "food", "kenney"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },

  // ---------------- target (2) — fruit-puzzle'ın basket_red/basket_green
  // ile AYNI "game-object + gameplayRole:target" deseni. ----------------
  {
    id: "foodkit_plate",
    path: "/assets/packs/food-kit/objects/plate.png",
    category: "game-object",
    name: "Plate",
    tags: ["plate", "container", "target", "food", "kenney"],
    gameplayRole: ["target", "container"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_cutting_board",
    path: "/assets/packs/food-kit/objects/cutting-board.png",
    category: "game-object",
    name: "Cutting Board",
    tags: ["cutting-board", "container", "target", "food", "kenney"],
    gameplayRole: ["target", "container"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },

  // ---------------- gameObject (3 mutfak aleti) ----------------
  {
    id: "foodkit_pot",
    path: "/assets/packs/food-kit/objects/pot.png",
    category: "game-object",
    name: "Cooking Pot",
    tags: ["pot", "cooking", "kitchen", "tool", "food", "kenney"],
    gameplayRole: ["gameObject"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_frying_pan",
    path: "/assets/packs/food-kit/objects/frying-pan.png",
    category: "game-object",
    name: "Frying Pan",
    tags: ["pan", "frying-pan", "cooking", "kitchen", "tool", "food", "kenney"],
    gameplayRole: ["gameObject"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_cooking_knife",
    path: "/assets/packs/food-kit/objects/cooking-knife.png",
    category: "game-object",
    name: "Cooking Knife",
    tags: ["knife", "cooking", "kitchen", "tool", "food", "kenney"],
    gameplayRole: ["gameObject"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },

  // ---------------- decoration (4 hazır yemek) — SADECE gerçek (LLM)
  // üretimde görünür (mock tüketmiyor, diğer kitlerin decoration rolüyle
  // aynı desen). ----------------
  {
    id: "foodkit_burger",
    path: "/assets/packs/food-kit/objects/burger.png",
    category: "game-object",
    name: "Burger",
    tags: ["burger", "dish", "scenery", "decoration", "food", "kenney"],
    gameplayRole: ["decoration"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_pizza",
    path: "/assets/packs/food-kit/objects/pizza.png",
    category: "game-object",
    name: "Pizza",
    tags: ["pizza", "dish", "scenery", "decoration", "food", "kenney"],
    gameplayRole: ["decoration"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_cake",
    path: "/assets/packs/food-kit/objects/cake.png",
    category: "game-object",
    name: "Cake",
    tags: ["cake", "dessert", "scenery", "decoration", "food", "kenney"],
    gameplayRole: ["decoration"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
  {
    id: "foodkit_donut",
    path: "/assets/packs/food-kit/objects/donut.png",
    category: "game-object",
    name: "Donut",
    tags: ["donut", "dessert", "scenery", "decoration", "food", "kenney"],
    gameplayRole: ["decoration"],
    compatibleGameTypes: ["cooking"],
    visualStyle: "kenney-food-kit-v1",
    theme: "cooking",
    pack: "food-kit",
    animationType: "static",
  },
];

module.exports = { FOOD_KIT_ASSETS: FOOD_KIT_ASSETS };
